platform :ios, "8"

pod "AFNetworking"
pod "SDWebImage"
pod "MJExtension"
pod "MJRefresh"
pod "BlocksKit"
pod "MBProgressHUD"
pod "Masonry"
pod "RESideMenu"
pod "FMDB"
pod "CocoaAsyncSocket"
pod "YYText"
